export const customerNames = [
  "Aarav Sharma",
  "Vivaan Gupta",
  "Aditya Singh",
  "Arjun Mehta",
  "Rohan Verma",
  "Kabir Malhotra",
  "Aryan Kapoor",
  "Ishaan Khanna",
  "Dev Bansal",
  "Yash Agarwal",
  "Rahul Kumar",
  "Karan Sethi",
  "Ankit Jain",
  "Mohit Sharma",
  "Nikhil Arora",
  "Varun Chopra",
  "Siddharth Rao",
  "Harsh Vardhan",
  "Akash Yadav",
  "Manish Tiwari",
  "Priya Sharma",
  "Ananya Gupta",
  "Isha Mehta",
  "Neha Verma",
  "Riya Kapoor",
  "Sneha Malhotra",
  "Simran Kaur",
  "Pooja Arora",
  "Kritika Jain",
  "Shreya Singh",
  "Aditi Khanna",
  "Nandini Bansal",
  "Muskan Agarwal",
  "Tanya Sethi",
  "Sakshi Rao",
  "Megha Chopra",
  "Ritika Yadav",
  "Kavya Tiwari",
  "Diya Sharma",
  "Manya Gupta",
  "Radhika Mehta",
  "Nisha Verma",
  "Palak Kapoor",
  "Ayesha Khan",
  "Zoya Ali",
  "Meera Nair",
  "Shivani Joshi",
  "Tanvi Reddy",
  "Sanya Arora",
  "Anushka Jain",
  "Khushi Singh",
];

export const cities = [
  "Delhi",
  "Gurgaon",
  "Noida",
  "Faridabad",
  "Ghaziabad",
];

export const services = [
  {
    name: "Oil Change",
    category: "Maintenance",
    minPrice: 800,
    maxPrice: 1800,
  },
  {
    name: "Car Battery Replacement",
    category: "Electrical",
    minPrice: 2500,
    maxPrice: 6500,
  },
  {
    name: "Brake Inspection",
    category: "Brakes",
    minPrice: 700,
    maxPrice: 2500,
  },
  {
    name: "AC Service",
    category: "AC & Cooling",
    minPrice: 1200,
    maxPrice: 4500,
  },
  {
    name: "Engine Diagnostics",
    category: "Diagnostics",
    minPrice: 1000,
    maxPrice: 3500,
  },
  {
    name: "Tyre Replacement",
    category: "Tyres",
    minPrice: 3000,
    maxPrice: 12000,
  },
  {
    name: "Car Wash & Detailing",
    category: "Cleaning",
    minPrice: 600,
    maxPrice: 3000,
  },
  {
    name: "General Service",
    category: "Maintenance",
    minPrice: 1500,
    maxPrice: 6000,
  },
];

export const vehicles = [
  { make: "Maruti", model: "Swift" },
  { make: "Maruti", model: "Baleno" },
  { make: "Hyundai", model: "Creta" },
  { make: "Hyundai", model: "i20" },
  { make: "Tata", model: "Nexon" },
  { make: "Tata", model: "Punch" },
  { make: "Mahindra", model: "XUV700" },
  { make: "Mahindra", model: "Scorpio" },
  { make: "Toyota", model: "Fortuner" },
  { make: "Honda", model: "City" },
  { make: "Kia", model: "Seltos" },
  { make: "Volkswagen", model: "Virtus" },
];

export const mechanicNames = [
  "Rajesh Kumar",
  "Suresh Yadav",
  "Amit Sharma",
  "Vikas Singh",
  "Deepak Verma",
  "Manoj Gupta",
  "Ravi Kumar",
  "Pankaj Mehta",
  "Sunil Chauhan",
  "Ashok Sharma",
  "Vijay Singh",
  "Rakesh Kumar",
  "Naveen Yadav",
  "Sachin Verma",
  "Gaurav Gupta",
  "Anil Sharma",
  "Dinesh Kumar",
  "Mukesh Singh",
  "Rohit Yadav",
  "Pradeep Kumar",
  "Sanjay Verma",
  "Aakash Sharma",
];

export const initialUsers = [
  {
    name: "System Admin",
    email: "admin@instantmechanic.com",
    password: "AdminPassword123!",
    role: "admin" as const,
  },
  {
    name: "Operations Manager",
    email: "ops@instantmechanic.com",
    password: "OpsPassword123!",
    role: "operations" as const,
  },
];